### ISSUE TITLE
Error trying to import to json (Jira Data Center)

### ISSUE THREAD

**Issue by largui** [princenyeche/jiraone#122]
Hello Support,
I am trying to export json file on Jira DC. I got this issue:

Exception in thread Thread-4 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-1 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-5 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-13 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
Exception in thread Thread-12 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-14 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-16 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-18 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-17 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-20 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-21 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-15 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-22 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-23 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-24 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-19 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-25 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
Exception in thread Thread-26 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    "key": a["key"],
KeyError: 'key'
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-27 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-28 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-30 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-29 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-33 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-35 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-34 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-36 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3673, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3606, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-31 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-32 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3688, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3598, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-38 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 3673, in float_fields
    map_name = field.get_field(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/access.py", line 3606, in get_field
    "key": a["key"],
KeyError: 'key'
Exception in thread Thread-37 (float_fields):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()

For CSV no issues. All good.

### Code ###
LOGIN.api = False
fields = []
jql = "project in (XPN) order by created DESC"
issue_export(jql=jql, extension="json", fields=fields)

Thanks and regards,
Sergio

**Comment by princenyeche** [comment]
Hey @largui 

I'm working on releasing version **0.7.9** which should solve this problem and improve the performance for the JSON export. It should be released before or on this weekend.

**Comment by largui** [comment]
Hello @princenyeche ,
Thanks for your update. 
I will be waiting for that.

Regards

**Comment by princenyeche** [comment]
Hey @largui the new version is out, please let me know if all the issues you encountered before are resolved.

**Comment by largui** [comment]
Hey @princenyeche, I will check it right away and I will let you know.

**Comment by largui** [comment]
Hello @princenyeche,

I got this error now with the latest version 0.8.2:
Downloading issue export in JSON format.
<Response [200]>  ::downloading issues at page: 0 of 1
<Response [200]>  ::downloading issues at page: 1 of 1
Processing. Current progress: 50%
Processing. Current progress: 100%
Converting Jira custom field names to Jira JSON compatible names.
Verifying users membership
Searching for user data.
Verifying Sprint values.
Extracting Sprint Ids from values.
Searching for Sprint data
JSON conversion started.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 6935, in json_field_builder
    field_builder(
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 6928, in field_builder
    start_process()
  File "/usr/local/lib/python3.10/dist-packages/jiraone/reporting.py", line 6545, in start_process
    if not obj_name.get("column_name").startswith(
AttributeError: 'NoneType' object has no attribute 'startswith'
An error has occurred: 'NoneType' object has no attribute 'startswith'

**Comment by princenyeche** [comment]
Hi @largui, it seems there's an issue with the field extraction at that specific code section, or possibly due to some other factor. This error shouldn't happen because, by this point in the script, it should already be aware of the names and properties of both system and custom fields you have. Could you inform me whether there were any additional temporary files in the folder where the extraction occurred before you executed the script?

**Comment by largui** [comment]
Hi @princenyeche, 
I checked it and there is no any temporary files in the folder. I removed export and logs ones to be recreated again. This is my script:

from jiraone import LOGIN, issue_export
import os

your_cert_path = "Caroot.crt"
os.environ["REQUESTS_CA_BUNDLE"] = your_cert_path
# before calling jiraone statements
LOGIN.api = False
LOGIN = LOGIN("admin", "Password", "https://myjira.com")
fields = []
jql = "project in (XPN) order by created DESC"
issue_export(jql=jql, extension="json", fields=fields, final_file="backup")

**Comment by princenyeche** [comment]
@largui I'm unsure what the actual cause might be at the moment with the data being `None` but can you attempt the below steps as that might give me a hunch of what might be happening

 - Run your export but with a CSV option at first
```python
# previous expressions
jql = "project in (XPN) order by created DESC"
issue_export(jql=jql, extension="csv", fields=fields, final_file="backup")
```
- Immediately on the next line in the code, attempt the conversion to JSON using 
```python
# previous code example
issue_export(csv_to_json="backup.csv", fields=fields, final_file="backup")
```
Let me know if you get the same error or a different one?

**Comment by largui** [comment]
Defaulting to comma as CSV separator.
Downloading issue export in CSV format.
<Response [200]>  ::downloading issues at page: 0 of 10
<Response [200]>  ::downloading issues at page: 1 of 10
<Response [200]>  ::downloading issues at page: 2 of 10
<Response [200]>  ::downloading issues at page: 3 of 10
<Response [200]>  ::downloading issues at page: 4 of 10
<Response [200]>  ::downloading issues at page: 5 of 10
<Response [200]>  ::downloading issues at page: 6 of 10
<Response [200]>  ::downloading issues at page: 7 of 10
<Response [200]>  ::downloading issues at page: 8 of 10
<Response [200]>  ::downloading issues at page: 9 of 10
<Response [200]>  ::downloading issues at page: 10 of 10
Processing. Current progress: 9%
Processing. Current progress: 18%
Processing. Current progress: 27%
Processing. Current progress: 36%
Processing. Current progress: 45%
Processing. Current progress: 54%
Processing. Current progress: 63%
Processing. Current progress: 72%
Processing. Current progress: 81%
Processing. Current progress: 90%
Processing. Current progress: 100%
Export Completed.File located at /scripts/datacenter/EXPORT/backup.csv
Defaulting to comma as CSV separator.
Traceback (most recent call last):
  File "/scripts/datacenter/exportv2.py", line 16, in <module>
    issue_export(csv_to_json="backup.csv", fields=fields, final_file="backup")
  File "/home/sleondelarosa/.local/lib/python3.10/site-packages/jiraone/reporting.py", line 3494, in export_issues
    validate_on_error(
  File "/home/sleondelarosa/.local/lib/python3.10/site-packages/jiraone/utils.py", line 315, in validate_on_error
    raise JiraOneErrors(
jiraone.exceptions.JiraOneErrors: <JiraOneError: The `jql` argument should be a string of a valid Jira query.Detected <class 'NoneType'> instead.>

**Comment by largui** [comment]
Another question: Is it possible to use token instead of password? 
I trying this in Login:
LOGIN = LOGIN("admin", "Token", "https://myjira.com") but I got credentials error_
Traceback (most recent call last):
  File "/scripts/datacenter/exportv2.py", line 15, in <module>
    issue_export(jql=jql, extension="csv", fields=fields, final_file="backup")
  File "/home/sleondelarosa/.local/lib/python3.10/site-packages/jiraone/reporting.py", line 3136, in export_issues
    raise JiraOneErrors(
jiraone.exceptions.JiraOneErrors: <JiraOneError: Authentication failed. Please check your credentials. Reason: >

What am I missing?

**Comment by princenyeche** [comment]
Hey @largui 

Try the below, I forgot to include the jql parameter and the check_auth parameter
```python
# previous code example
issue_export(csv_to_json="backup.csv", fields=fields, final_file="backup", jql=jql, check_auth=False)
```
Yes, you can use PAT as mentioned [here](https://jiraone.readthedocs.io/en/latest/api.html#login) under bearer authentication

**Comment by largui** [comment]
Outuput: 
Defaulting to comma as CSV separator.
Downloading issue export in CSV format.
<Response [200]>  ::downloading issues at page: 0 of 0
Processing. Current progress: 100%
Export Completed.File located at /scripts/datacenter/EXPORT/backup.csv
Defaulting to comma as CSV separator.
Downloading issue export in CSV format.
Processing. Current progress: 100%
Export Completed.File located at /scripts/datacenter/EXPORT/backup.csv

But the export folder is empty
sleondelarosa@JALS:/scripts/datacenter$ ls -tlr EXPORT/
total 0

**Comment by princenyeche** [comment]
That's not the expected behaviour, I'll correct that later on but do

```python
# previous code example
issue_export(csv_to_json="backup.csv", fields=fields, final_file="backup", extension="json")
```
Apologies for the back and forth. Kindly include the `extension` argument to ensure recognition of the JSON part. Feel free to reach out if the `NoneType` error persists. In case it does, examine the CSV export (you can generate a CSV separately, as the script will delete the old file). Open the file and check for any missing columns or columns without names then let me know what you find out.

**Comment by largui** [comment]
Defaulting to comma as CSV separator.
Downloading issue export in CSV format.
<Response [200]>  ::downloading issues at page: 0 of 10
<Response [200]>  ::downloading issues at page: 1 of 10
<Response [200]>  ::downloading issues at page: 2 of 10
<Response [200]>  ::downloading issues at page: 3 of 10
<Response [200]>  ::downloading issues at page: 4 of 10
<Response [200]>  ::downloading issues at page: 5 of 10
<Response [200]>  ::downloading issues at page: 6 of 10
<Response [200]>  ::downloading issues at page: 7 of 10
<Response [200]>  ::downloading issues at page: 8 of 10
<Response [200]>  ::downloading issues at page: 9 of 10
<Response [200]>  ::downloading issues at page: 10 of 10
Processing. Current progress: 9%
Processing. Current progress: 18%
Processing. Current progress: 27%
Processing. Current progress: 36%
Processing. Current progress: 45%
Processing. Current progress: 54%
Processing. Current progress: 63%
Processing. Current progress: 72%
Processing. Current progress: 81%
Processing. Current progress: 90%
Processing. Current progress: 100%
Export Completed.File located at /scripts/datacenter/EXPORT/backup.csv
Traceback (most recent call last):
  File "/scripts/datacenter/exportv2.py", line 17, in <module>
    issue_export(csv_to_json="backup.csv", fields=fields, final_file="backup", extension="json")
  File "/home/sleondelarosa/.local/lib/python3.10/site-packages/jiraone/reporting.py", line 3494, in export_issues
    validate_on_error(
  File "/home/sleondelarosa/.local/lib/python3.10/site-packages/jiraone/utils.py", line 315, in validate_on_error
    raise JiraOneErrors(
jiraone.exceptions.JiraOneErrors: <JiraOneError: The `jql` argument should be a string of a valid Jira query.Detected <class 'NoneType'> instead.>

**Comment by largui** [comment]
One more question @princenyeche,
Is there any constraint in the number of issues to export using CSV file? I going to test to export to CSV file around 120000 issues
I suppose that this take time and nothing more, right?

Thanks for your support

**Comment by princenyeche** [comment]
No constraint, just the time you've taken. Did you get your JSON file sorted out? 
```python
# previous code example
issue_export(csv_to_json="backup.csv", fields=fields, final_file="backup", extension="json", jql=jql)
```
There are some behaviours with this method that are not working well when combined, added to my backlog for things to fix in the next release.

**Comment by largui** [comment]
Same issue:
Defaulting to comma as CSV separator.
Downloading issue export in CSV format.
<Response [200]>  ::downloading issues at page: 0 of 10
<Response [200]>  ::downloading issues at page: 1 of 10
<Response [200]>  ::downloading issues at page: 2 of 10
<Response [200]>  ::downloading issues at page: 3 of 10
<Response [200]>  ::downloading issues at page: 4 of 10
<Response [200]>  ::downloading issues at page: 5 of 10
<Response [200]>  ::downloading issues at page: 6 of 10
<Response [200]>  ::downloading issues at page: 7 of 10
<Response [200]>  ::downloading issues at page: 8 of 10
<Response [200]>  ::downloading issues at page: 9 of 10
<Response [200]>  ::downloading issues at page: 10 of 10
Processing. Current progress: 9%
Processing. Current progress: 18%
Processing. Current progress: 27%
Processing. Current progress: 36%
Processing. Current progress: 45%
Processing. Current progress: 54%
Processing. Current progress: 63%
Processing. Current progress: 72%
Processing. Current progress: 81%
Processing. Current progress: 90%
Processing. Current progress: 100%
Export Completed.File located at /scripts/datacenter/EXPORT/backup.csv
Downloading issue export in JSON format.
Processing. Current progress: 100%
Converting Jira custom field names to Jira JSON compatible names.
Verifying users membership
Searching for user data.
Verifying Sprint values.
Extracting Sprint Ids from values.
Searching for Sprint data
JSON conversion started.
Traceback (most recent call last):
  File "/home/sleondelarosa/.local/lib/python3.10/site-packages/jiraone/reporting.py", line 6935, in json_field_builder
    field_builder(
  File "/home/sleondelarosa/.local/lib/python3.10/site-packages/jiraone/reporting.py", line 6928, in field_builder
    start_process()
  File "/home/sleondelarosa/.local/lib/python3.10/site-packages/jiraone/reporting.py", line 6545, in start_process
    if not obj_name.get("column_name").startswith(
AttributeError: 'NoneType' object has no attribute 'startswith'
An error has occurred: 'NoneType' object has no attribute 'startswith'

**Comment by princenyeche** [comment]
Hopefully, in the next release cycle, I'll revisit this issue when I have more time to dive into the likely cause of the `NoneType` value. I think it's a field without a proper column name but I'm uncertain. I probably need to validate all field properties before they reach that line in the code. I don't have an ETA but I'll work on it as soon as I can.

**Comment by largui** [comment]
Ok, thanks. I am looking forward to hear from you soon

**Comment by kalupator** [comment]
Hello everyone!
Is there a solution to the problem:
**An error has occurred: 'NoneType' object has no attribute 'startswith'**
Unfortunately, I can't export any of my projects in json format

```
JSON conversion started.
The default CSV separator is a comma for the delimit argument, no action taken.Traceback (most recent call last):
  File "C:\Program Files\Python\Python313\Lib\site-packages\jiraone\reporting.py", line 7019, in json_field_builder
    field_builder(
    ~~~~~~~~~~~~~^
        name_of_fields,
        ^^^^^^^^^^^^^^^
        config["headers"],
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Program Files\Python\Python313\Lib\site-packages\jiraone\reporting.py", line 7012, in field_builder
    start_process()
    ~~~~~~~~~~~~~^^
  File "C:\Program Files\Python\Python313\Lib\site-packages\jiraone\reporting.py", line 6629, in start_process
    if not obj_name.get("column_name").startswith(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
An error has occurred: 'NoneType' object has no attribute 'startswith'
Exception in thread Thread-55 (search_sprints):
Traceback (most recent call last):
  File "C:\Program Files\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Program Files\Python\Python313\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python313\Lib\site-packages\jiraone\reporting.py", line 5483, in search_sprints
    sprint_item_.get("name")
    ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

**Comment by princenyeche** [comment]
Hey @largui, I'll be working on this next month and will provide a fix for this issue.

**Comment by princenyeche** [comment]
@kalupator there's no workaround yet. I'll work on troubleshooting the error and provide a fix by next month.

**Comment by kalupator** [comment]
> @kalupator there's no workaround yet. I'll work on troubleshooting the error and provide a fix by next month.

@princenyeche Thank you very much for your work!
I will be looking forward to the update.

In the meantime, I am trying to load the project via csv and also encountered a number of problems. Please tell me how I can ask questions about the problems I encountered when importing csv? Do I need to create a new issue (or several issues)?

**Comment by princenyeche** [comment]
You can create a new issue about the problem with error logs describing the action you took before the problem happened, and then I can review it.

**Comment by princenyeche** [comment]
@largui, I'm sorry for the long wait. I've pushed a new version, which could fix this issue. Please test it out and let me know if it solves the issue for you

@kalupator, this should work the same for you. Try it out and let me know if the JSON export issue is resolved.

**Comment by kalupator** [comment]
@princenyeche 
I updated the jiraone:
> Successfully installed jiraone-0.8.6

The old error remains:
> An error has occurred: 'NoneType' object has no attribute 'startswith'

and another one has been added:
> Exception` in thread Thread-53 (search_sprints):

it wasn't there before (above was my previous error output).

First error:

```
The default CSV separator is a comma for the delimit argument, no action taken.Exception in thread Thread-54 (search_sprints):
**Exception in thread Thread-53 (search_sprints):**
Traceback (most recent call last):
  File "C:\Program Files\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Program Files\Python\Python313\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python313\Lib\site-packages\jiraone\reporting.py", line 5483, in search_sprints
    sprint_item_.get("name")
    ^^^^^^^^^^^^^^^^
Traceback (most recent call last):
AttributeError: 'str' object has no attribute 'get'
  File "C:\Program Files\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Program Files\Python\Python313\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Python313\Lib\site-packages\jiraone\reporting.py", line 5483, in search_sprints
    sprint_item_.get("name")
    ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

And then second error:

```
JSON conversion started.
Traceback (most recent call last):
  File "C:\Program Files\Python\Python313\Lib\site-packages\jiraone\reporting.py", line 7019, in json_field_builder
    field_builder(
    ~~~~~~~~~~~~~^
        name_of_fields,
        ^^^^^^^^^^^^^^^
        config["headers"],
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Program Files\Python\Python313\Lib\site-packages\jiraone\reporting.py", line 7012, in field_builder
    start_process()
    ~~~~~~~~~~~~~^^
  File "C:\Program Files\Python\Python313\Lib\site-packages\jiraone\reporting.py", line 6629, in start_process
    if not obj_name.get("column_name", "").startswith(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
An error has occurred: 'NoneType' object has no attribute 'startswith'
```

**Comment by kalupator** [comment]
@princenyeche 
Maybe I can provide you with more information for analysis?

**Comment by princenyeche** [comment]
@kalupator that would be very helpful, Thanks. I'll post a message to you, once I've pushed the PR.

**Comment by princenyeche** [comment]
Hey @kalupator Hope you're doing well. About this issue, I just pushed this [branch](https://github.com/princenyeche/jiraone/tree/princenyeche-patch-1). Please help me test it out and check if the error still occurs. I think the reason this happens is due to a field that has a null value. I'm not sure how a field name can be null, but this change is to bypass such an error and still return a string.

**Comment by princenyeche** [comment]
Hi @kalupator I'm good. Yeah, there shouldn't be much difference between 8 and 10. Thanks for the error stack, I updated the branch again. Please help and check again, when you have the time. This should bypass any field that may be unknown.

**Comment by kalupator** [comment]
@princenyeche, now an error occurs:

```
Downloading issue export in JSON format.
<Response [200]>  ::downloading issues at page: 0 of 0
Processing. Current progress: 100%
Reconstructing file headers
Applying updated data into the CSV file
Converting Jira custom field names to Jira JSON compatible names.
Verifying users membership
Searching for user data.
Verifying Sprint values.
Extracting Sprint Ids from values.
Searching for Sprint data
JSON conversion started.
The default CSV separator is a comma for the delimit argument, no action taken.Traceback (most recent call last):
  File "C:\Program Files\Python\Python313\Lib\site-packages\jiraone\reporting.py", line 7028, in json_field_builder
    field_builder(
    ~~~~~~~~~~~~~^
        name_of_fields,
        ^^^^^^^^^^^^^^^
        config["headers"],
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Program Files\Python\Python313\Lib\site-packages\jiraone\reporting.py", line 7021, in field_builder
    start_process()
    ~~~~~~~~~~~~~^^
  File "C:\Program Files\Python\Python313\Lib\site-packages\jiraone\reporting.py", line 6859, in start_process
    if _issue_key.startswith("Custom field"):
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
An error has occurred: 'NoneType' object has no attribute 'startswith'
```

**Comment by princenyeche** [comment]
Thanks for your help on this @kalupator I updated the branch again, this time I updated `utils.py` and `reporting.py`.

**Comment by kalupator** [comment]
@princenyeche, next error occurs:
```
Downloading issue export in JSON format.
<Response [200]>  ::downloading issues at page: 0 of 0
Processing. Current progress: 100%
Reconstructing file headers
Applying updated data into the CSV file
Converting Jira custom field names to Jira JSON compatible names.
Verifying users membership
Searching for user data.
Verifying Sprint values.
Extracting Sprint Ids from values.
Searching for Sprint data
JSON conversion started.
Clearing temporary configuration data
The default CSV separator is a comma for the delimit argument, no action taken.Traceback (most recent call last):
  File "C:\Program Files\Python\Python313\Lib\site-packages\jiraone\reporting.py", line 7308, in export_issues
    extend_format(extension)
    ~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Program Files\Python\Python313\Lib\site-packages\jiraone\reporting.py", line 7233, in extend_format
    extend_file_type()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Program Files\Python\Python313\Lib\site-packages\jiraone\reporting.py", line 5549, in extend_file_type
    json.dump(
    ~~~~~~~~~^
        config["json_build"],
        ^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
        sort_keys=True,
        ^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Program Files\Python\Python313\Lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
                 ^^^^^^^^
  File "C:\Program Files\Python\Python313\Lib\json\encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Program Files\Python\Python313\Lib\json\encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "C:\Program Files\Python\Python313\Lib\json\encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "C:\Program Files\Python\Python313\Lib\json\encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "C:\Program Files\Python\Python313\Lib\json\encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "C:\Program Files\Python\Python313\Lib\json\encoder.py", line 354, in _iterencode_dict
    items = sorted(dct.items())
TypeError: '<' not supported between instances of 'str' and 'NoneType'
An error has occurred: '<' not supported between instances of 'str' and 'NoneType'

```

**Comment by princenyeche** [comment]
This is the hardest part, knowing exactly where the noneType is in the JSON object. I have to retrace the steps and start from scratch to identify why it's even noneType in the first place and discard it. Thanks for your help so far @kalupator
